### ISSUE TITLE
failed with exit status 0xffffffff

### ISSUE THREAD

**Issue by creeper-0910** [Tylous/Limelighter#7]
Hello.
I ran Limelighter and got the following error
```
cmd.Run() failed with exit status 0xffffffff
```
I would appreciate it if you know the solution.

**Comment by Tylous** [comment]
I need more information but I suspect it could not route to the domain you specified.

**Comment by 16BitS3G4l** [comment]
Not sure if this was correct at the time, but I've encountered the same error which was not caused by resolving the domain.

Instead, it was caused by a failure to complete the SignExecutable function.

More specifically, ```osslsigncode```  returns a failure for the provided PFX password.

Again, not sure if this is relevant but it is currently an issue I'm facing which doesn't seem to have any relation to resolving the domain.

I believe reopening this issue would be prudent @Tylous
